# This is a manually called scheduling job that calls another GitHub Actions YAML file to run at a relative time to the launch of this job (or scheduled time), it uses the linux AT command.

name: GitHub Actions Workflow scheduler to run an adhoc action at a time relative to now
run-name: ${{ github.actor }} is scheduling a GitHub Action to run later🚀

on: 
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run action-to-run.yml | at now
      - run: gh workflow run action-to-run.yml | at now +5 minutes
      - run: gh workflow run action-to-run.yml | at now +10 minutes
      - run: gh workflow run action-to-run.yml | at 1:45 081223
      - run: gh workflow run action-to-run.yml | at 3pm + 4 days
      - run: gh workflow run action-to-run.yml | at -m 4:30    
      - run: gh workflow run action-to-run.yml | at 3:45 042723      
      
