# This is a manually called scheduling job that calls another GitHub Actions YAML file to run at a relative time to the launch of this job (or scheduled time), it uses the linux AT command.

# Repo Settings permissions: Change Settings -> Actions -> General -> Workflow Permissions to allow read and write, as per: https://github.com/actions/first-interaction/issues/10

# Manually launch this job, and it will schedule and launch the other jobs.

name: GitHub Actions Workflow scheduler to run an adhoc action at a time relative to now
run-name: ${{ github.actor }} is scheduling a GitHub Action to run later🚀

on: 
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y at
      - name: Check out repository code
        uses: actions/checkout@v3
#      - run: gh workflow run action-to-run.yml | at now
      - run: at now +5 minutes | gh workflow run action-to-run.yml
#      - run: gh workflow run action-to-run.yml | at now +10 minutes
#      - run: gh workflow run action-to-run.yml | at 3pm + 4 days
#      - run: gh workflow run action-to-run.yml | at -m 4:30
#      - run: gh workflow run action-to-run.yml | at 15:45 042723
#      - run: gh workflow run action-to-run.yml | at 1:45 081223
